[functions]
  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  Referrer-Policy = "no-referrer-when-downgrade"
  X-XSS-Protection = "1; mode=block"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  Cross-Origin-Embedder-Policy = "require-corp"
